---
ssh_port: "{{ hostvars[groups['test'][0]]['ansible_ssh_port'] }}"
private_key_file: "{{ hostvars[groups['test'][0]]['ansible_ssh_private_key_file'] }}"
cur_dir: "{{ lookup('env','PWD') }}"
user: "{{ hostvars[groups['test'][0]]['ansible_ssh_user'] }}"
install_xcode_script: install-xcode-console.sh

projects_home_dir: /home/{{ user }}/go/src

homebrew_cask_appdir: /usr/local/opt

homebrew_taps:
  - caskroom/cask
  - caskroom/versions

homebrew_packages:
  - ansible
  - asciidoc
  - automake
  - bash-completion
  - cmake
  - csvkit
  - fzf
  - gcc
  - git
  - glib
  - glide
  - gradle
  - groovy
  - go
  - htop
  - htop-osx
  - httpie
  - iftop
  - ipython
  - jq
  - kotlin
  - libtool
  - libxml2
  - libyaml
  - mc
  - mongodb
  - nmap
  - ntfs-3g
  - openssl
  - postgresql
  - python
  - python@2
  - sysdig
  - ranger
  - readline
  - rlwrap
  - sbt
  - sqlite
  - sysdig
  - tmux
  - wget
  - zsh
  - zsh-autosuggestions
  - zsh-completions
  - editorconfig
  - yq
  - virtualenv
  - j2
  - jinja2-cli
  - openvpn
  - 

homebrew_cask_apps:
  - java8
  - google-chrome
  - docker
  - dropbox
  - emacs
  - intellij-idea-ce
  - iterm2
  - macports
  - openoffice
  - osxfuse
  - telegram
  - vagrant
  - virtualbox
  - wireshark

emacs_langs:
  - go
  - java
  - python
  - php
  - sh
  - c
